In [2]:
import numpy as np

In [3]:
# create - from list
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D, type(arr2D), arr2D.shape, arr2D.size)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3) 9


In [20]:
# Craete from stratch
arr1 = np.zeros((2, 3), dtype="int64") #Prefill with 0 wala 2D array hai yeh
print(arr1, arr1.shape)

arr1 = np.ones((2, 3), dtype="int64") #Prefill with 1s wala 2D array hai yeh
print(arr1, arr1.shape)

arr2 = np.ones((5, ), dtype="int64") #Prefill with 0 wala 2D array hai yeh
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 100) #Prefill with value
print(arr3, arr3.shape)

arr4 = np.eye(3) #Identity matrix
print(arr4, arr4.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[1 1 1 1 1] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
