In [18]:
import numpy as np

In [19]:
# create - from list
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D, type(arr2D), arr2D.shape, arr2D.size)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3) 9


In [20]:
# Create from stratch
arr1 = np.zeros((2, 3), dtype="int64") #Prefill with 0 wala 2D array hai yeh
print(arr1, arr1.shape)

arr1 = np.ones((2, 3), dtype="int64") #Prefill with 1s wala 2D array hai yeh
print(arr1, arr1.shape)

arr2 = np.ones((5, ), dtype="int64") #Prefill with 0 wala 2D array hai yeh
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 100) #Prefill with value
print(arr3, arr3.shape)

arr4 = np.eye(3) #Identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 11, 2) #arange function
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 4) #Evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[1 1 1 1 1] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [21]:
# Properties
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

print(arr.shape)  #tells about the dimension = m x n
print(arr.size)   #Tells the number of elements in the array
print(arr.dtype)
print(arr.ndim)  #Tell the total number of dimension we have

#TypeCasting in array
# float_arr = arr.astype(str)    #integer to string typecasting
float_arr = arr.astype(np.float64)    #integer to float typecasting
print(float_arr, float_arr.dtype)

(2, 5)
10
int64
2
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]] float64


In [22]:
# Operations on NumPy arrays

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened = arr.flatten() #2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [23]:
# Indexing
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[0], arr[1], arr[2])

# for 2D array
arr2D = np.array([[1, 2, 3],[4, 5, 6]])
print(arr2D[0][2])

# Fancy indexing
arr = np.array([1, 2, 3, 4, 5, 6])

idx = [0, 1, 3]
print(arr[idx])

# Boolean indexing
new = np.array([1,2,3,4,5])

print(arr[arr > 2])
print(arr[arr % 2 == 0])

1 2 3
3
[1 2 4]
[3 4 5 6]
[2 4 6]


In [24]:
# Slicing 
arr =  np.array([1, 2, 3, 4, 5])

print(arr[1:4]) #[start , end , step]
print(arr[1:])
print(arr[:4:2])

[2 3 4]
[2 3 4 5]
[1 3]


In [25]:
# Copy vs View
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3].copy()
print(sub_arr)
sub_arr[0] = 200

print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[1 2 3 4 5]


In [27]:
# Data Types
arr = np.array([1,2,3,4,5.4, "print"])
com_arr = np.array([3+5j])

print(com_arr,com_arr.dtype)
print(arr, arr.dtype)

[3.+5.j] complex128
['1' '2' '3' '4' '5.4' 'print'] <U32


In [37]:
# Multidimensional Arrays

arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_column = np.sum(arr2D, axis = 0)
print(sum_of_column)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [51]:
# 3D array

arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])  #2 x 3 x 2

print(arr3D, arr3D.shape)

# Indexing
print(arr3D[0,1,1])

# Slicing
print(arr3D[:, 0, :])  #first  row from both layers
print(arr3D[:, :, 0])  #first  column from both layers
arr3D[:, 0, :] = 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [58]:
# Vectorization

arr = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([7, 8, 9, 10, 11, 12])

print(arr ** 2)
print(arr + 10)

arrt = arr + arr2

print(arrt)

[ 1  4  9 16 25 36]
[11 12 13 14 15 16]
[ 8 10 12 14 16 18]


In [68]:
# Broadcasting -> Scaling our array without using memory

# arr = np.array([[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6]])
arr = np.array([[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6]])
arr2 = np.array([[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6]])

print(arr.shape,arr2.shape)

print(arr + arr2)

(2, 6) (2, 6)
[[ 2  4  6  8 10 12]
 [ 2  4  6  8 10 12]]


In [74]:
# Vector normalization  -> STD normalization 
# Normalizing an array means tranforming its value so they fit into a specific scale or range

# Nomalize

arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr - mean) / std_dev
print(normalized_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [93]:
# Important Mathematical function

# Aggregation function

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.diff(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.median(arr))  #sorted order mei middle most data ko deta hai
print(np.std(arr))
print(np.var(arr))   #variance == square of standard deviation (std)

15
[1 1 1 1]
120
1
5
0
4
3.0
3.0
1.4142135623730951
2.0


In [97]:
# Power Functions

arr = np.array([1,2,3,4,5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [113]:
# logarithmic Functions

arr = np.array([1,2,3,4,5])

print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [118]:
# Rounding off

arr = np.array([1,2,3,4,5,-7,-9])

print(np.round(3.14))
print(np.ceil(9.3))   # -> Round up
print(np.floor(5.7))
print(np.trunc(7.182))

print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))


print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))

3.0
10.0
5.0
7.0
[-9 -7  1  2  3  4  5]
[-9 -7  1  2  3  4  5]
[1 2 3 4 5 7 9]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.6569866
 -0.41211849]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.75390225
 -0.91113026]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.87144798
  0.45231566]
